// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";

import "../../styles/home.css";
import "../../styles/menu.css";
import "../../styles/carta.css";
import "../../styles/registroLogin.css";
import "../../styles/formulario.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <div className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      {/* Script para toggle de tema */}
      <Script src="/js/darkmode.js" strategy="afterInteractive" />
      {children}
    </div>
  );
}
